### ISSUE TITLE
Initiative

### ISSUE THREAD

**Issue by docphil30** [12-Monkeys-Developers/ludiverse#1]
Impossible de lancer l'initiative

**Comment by Qaw** [comment]
Il n'y a pas vraiment d'initiative dans Ludiverse. Si tu veux vraiment gérer un ordre, il suffit d'éditer les initiatives manuellement pour mettre les valeurs voulues pour obtenir l'ordre voulue.

**Comment by docphil30** [comment]
Ah ok, je n’ai pas eu le temps de potasser les règles et je voulais tester les combats. Désolé ☹.
Par contre les fiches de personnages apparaissent chez moi avec un fond marron qui les rendent très peu lisibles. Je n’ai pourtant aucun autre module d’activé sur ce monde.
Cordialement,
Philippe Sallerin

Envoyé à partir de Courrier pour Windows

De : Christophe Laudon
Envoyé le :samedi 16 décembre 2023 17:11
À : 12-Monkeys-Developers/ludiverse
Cc : docphil30; Author
Objet :Re: [12-Monkeys-Developers/ludiverse] Initiative (Issue #1)

Il n'y a pas vraiment d'initiative dans Ludiverse. Si tu veux vraiment gérer un ordre, il suffit d'éditer les initiatives manuellement pour mettre les valeurs voulues pour obtenir l'ordre voulue.

**Comment by Qaw** [comment]
Tu parles du fond marron par défaut ? Est-ce que ça va mieux avec les autres "ambiances" que tu peux choisir dans les options du système ?
Tu peux aussi mettre ici des copies d'écran, plus simple pour nous de voir de quoi tu parles.

**Comment by docphil30** [comment]
Voilà ce que ça donne chez moi avec ou sans scène. C’est un problème récurrent de Foundry, c’est difficile avec Warhammer, par exemple, avec un fond bien dans le ton mais peu clair et impossible à changer sans tripoter le css.
Envoyé à partir de Courrier pour Windows

De : Christophe Laudon
Envoyé le :samedi 16 décembre 2023 18:31
À : 12-Monkeys-Developers/ludiverse
Cc : docphil30; Author
Objet :Re: [12-Monkeys-Developers/ludiverse] Initiative (Issue #1)

Tu parles du fond marron par défaut ? Est-ce que ça va mieux avec les autres "ambiances" que tu peux choisir dans les options du système ?
Tu peux aussi mettre ici des copies d'écran, plus simple pour nous de voir de quoi tu parles.

**Comment by Qaw** [comment]
Les images ne sont pas passées.

**Comment by docphil30** [comment]
Bizarre mais les voici à nouveau :


Envoyé à partir de Courrier pour Windows

De : Christophe Laudon
Envoyé le :vendredi 22 décembre 2023 17:28
À : 12-Monkeys-Developers/ludiverse
Cc : docphil30; Author
Objet :Re: [12-Monkeys-Developers/ludiverse] Initiative (Issue #1)

Les images ne sont pas passées.

**Comment by Qaw** [comment]
![image](https://github.com/12-Monkeys-Developers/ludiverse/assets/163632/85906b09-aeb5-4d45-95cb-1255b0e730c0)

Comme tu peux le voir : je ne vois pas tes images.

**Comment by Qaw** [comment]
Je pense comprendre ce dont tu parlais.
Corrigé dans la version 1.0.2

**Comment by docphil30** [comment]
:)
